# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from network import network_pb2 as network_dot_network__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='onet',
  syntax='proto2',
  serialized_pb=_b('\n\x0emessages.proto\x12\x04onet\x1a\x15network/network.proto\"N\n\x06Roster\x12\n\n\x02id\x18\x01 \x01(\x0c\x12%\n\x04list\x18\x02 \x03(\x0b\x32\x17.network.ServerIdentity\x12\x11\n\taggregate\x18\x03 \x02(\x0c')
  ,
  dependencies=[network_dot_network__pb2.DESCRIPTOR,])




_ROSTER = _descriptor.Descriptor(
  name='Roster',
  full_name='onet.Roster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='onet.Roster.id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list', full_name='onet.Roster.list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggregate', full_name='onet.Roster.aggregate', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=125,
)

_ROSTER.fields_by_name['list'].message_type = network_dot_network__pb2._SERVERIDENTITY
DESCRIPTOR.message_types_by_name['Roster'] = _ROSTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Roster = _reflection.GeneratedProtocolMessageType('Roster', (_message.Message,), dict(
  DESCRIPTOR = _ROSTER,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:onet.Roster)
  ))
_sym_db.RegisterMessage(Roster)


# @@protoc_insertion_point(module_scope)
