Suite = "Ed25519"
Hosts = ["127.0.0.1:2000", "127.0.0.1:2005", "127.0.0.1:2010"]
AggPubKey = ""
Ppm = 3
Bf = 1
Nmsgs = 0
Rate = 0
StampRatio = 1.0
Rounds = 0
Failures = 0
RFail = 0
FFail = 0
Debug = 2
StampsPerRound = -1
RootWait = 0
TestConnect = false

[Tree]
  Name = "127.0.0.1:2000"
  PriKey = ""
  PubKey = ""

  [[Tree.Children]]
    Name = "127.0.0.1:2005"
    PriKey = ""
    PubKey = ""

    [[Tree.Children.Children]]
      Name = "127.0.0.1:2010"
      PriKey = ""
      PubKey = ""
