Logger = ""
App = "medco"
AppDir = "/Users/khoffi/go/src/github.com/dedis/cothority/deploy/../app"
LocalDir = "/Users/khoffi/go/src/github.com/dedis/cothority/deploy"
RunDir = "/Users/khoffi/go/src/github.com/dedis/cothority/deploy/platform/localhost"
Debug = 2
Machines = 1
Ppm = 3
Hosts = ["127.0.0.1:2000", "127.0.0.1:2005", "127.0.0.1:2010"]
