notifications:
  email: false

language: go

install:
  - gimme 1.9
  - . $HOME/.gimme/envs/go1.9.env
  - go get github.com/dedis/Coding || true
  - go get -t ./...

before_install:
  - cd $TRAVIS_BUILD_DIR

script:
  - (cd conode/; make docker)
  - make test_playground
