matrix:
  include:
    - language: go

      install:
        - go get -t ./...
        - go get github.com/dedis/Coding || true

      before_install:
        - cd $TRAVIS_BUILD_DIR

      script:
        - make test_playground

    - language: node_js

      node_js:
        - "lts/*"
        - "8"

      env:
        - TEST_DIR=cothority
        - TEST_DIR=kyber

      install:
        - gimme 1.9
        - . $HOME/.gimme/envs/go1.9.env
        - go get github.com/dedis/Coding || true
        - git clone . `go env GOPATH`/src/github.com/dedis/cothority
        - (cd `go env GOPATH`/src/github.com/dedis/cothority && go get -t ./... )

      script:
        - cd external/js/$TEST_DIR && npm install && npm run test && npm run build

      after_success:
        - npm run coveralls

notifications:
  email: false
