dist: trusty

matrix:
  include:
    - language: go
      name: "Go Tests"

      go_import_path: go.dedis.ch/cothority/v3
 
      go:
        - "1.11.x"

      install:
        - go get github.com/dedis/Coding || true

      script:
        - env GO111MODULE=on make test

    - language: go
      name: "Go v1.10.x build"

      go_import_path: go.dedis.ch/cothority/v3
 
      go:
        - "1.10.x"

      script:
        - go get ./...
        - go build ./...

    - language: java
      name: "Java Tests"

      # This is needed because the "language: java" builder
      # defaults to Go 1.8 and does not respect the go version
      # specifier.
      install:
        - gimme 1.11
        - . $HOME/.gimme/envs/go1.11.env
        - env GO111MODULE=off go get github.com/dedis/Coding || true

      script:
        - make test_java

    - language: node_js
      name: "kyber-js Tests"
 
      node_js: "lts/*"
  
      script:
        - cd $TRAVIS_BUILD_DIR/external/js/kyber
        - npm install
        - npm run test
        - npm run build

after_success:
  - npm run coveralls

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
