# build script for dedis/cothority libraries
language: go
go:
  - 1.6
script:
  # formatting:
  - ./gofmt.sh
  # linter:
  - go get -u github.com/golang/lint/golint
  - ./lint.sh
  # check for missing error handling:
  #- go get -u github.com/kisielk/errcheck
  #- ./errcheck.sh
  # do not run any test binary in parallel (see go help build for more info on the -p flag)
  - go test -race -p=1 ./...

notifications:
  email: false