_:
  - &language_go_1_14
    name: "go 1.14"
    language: go
    go: "1.14.x"
  - &language_go_1_15
    name: "go 1.15"
    language: go
    go: "1.15.x"
  - &language_js
    language: node_js
    node_js: "lts/*"

  - &gen_link_kyber
    pushd external/js/kyber && npm ci && npm run link && popd
  - &get_go
    - gimme 1.14
    - . $HOME/.gimme/envs/go1.14.env

  - &stage_build_go
    script:
      - make -C conode bindist tooldist
      - GO111MODULE=on go build ./...
  - &stage_deploy_npm
    <<: *language_js
    before_deploy: echo "//registry.npmjs.org/:_authToken=${DEPLOY_NPM_TOKEN}" > $HOME/.npmrc
    script: skip  # default to `make test`

dist: trusty

stages:
  - test

jobs:
  include:
    - stage: test
      <<: *language_go_1_15
      script: GO111MODULE=on make test_playground

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
