language: go

install:
  - go get githib.com/dedis/onet
  - ( cd $GOPATH/src/github.com/dedis/onet ; git checkout p256 )
  - go get -t ./...
  - go get github.com/dedis/Coding || true

script:
  - make test

notifications:
  email: false
