#!/bin/bash

CSVS="shs2.csv smah.csv naive.csv naive_sc.csv"

#python plot_graph.py 0 shs2.csv smah.csv naive.csv naive_sc.csv comparison_roundtime.png
#python plot_graph.py 0 shs2.csv smah.csv naive.csv naive_sc.csv

#python plot_graph.py 1 shs2.csv smah.csv naive.csv naive_sc.csv comparison_systime.png
#python plot_graph.py 1 shs2.csv smah.csv naive.csv naive_sc.csv

#python plot_graph.py 3 $CSVS comparison_check.png
python plot_graph.py 3 $CSVS
