#!/bin/bash
#python plot_graph.py 0 shs2.csv smah.csv naive.csv naive_sc.csv comparison_roundtime.png
#python plot_graph.py 0 shs2.csv smah.csv naive.csv naive_sc.csv
#python plot_graph.py 1 shs2.csv smah.csv naive.csv naive_sc.csv comparison_systime.png
python plot_graph.py 1 shs2.csv smah.csv naive.csv naive_sc.csv
#python plot_graph.py 2 shs2.csv smah.csv comparison_systime_filled.png
