package debug_lvl
import (
	"fmt"
	"bytes"
	"github.com/Sirupsen/logrus"
	"os"
)

// These are information-debugging levels that can be turned on or off.
// Every logging greater than 'DebugVisible' will be discarded. So you can
// Log at different levels and easily turn on or off the amount of logging
// generated by adjusting the 'DebugVisible' variable.
var DebugVisible = 3

var DebugLog = &logrus.Logger{
	Out: os.Stdout,
	Formatter: &DebugLvl{},
	Hooks: make(logrus.LevelHooks),
	Level: logrus.InfoLevel}

func Lvl(lvl int, args ...interface{}) {
	DebugLog.WithField("debug_lvl", lvl).Println(args...)
}

func Lvl1(args ...interface{}) {
	Lvl(1, args...)
}

func Lvl2(args ...interface{}) {
	Lvl(2, args...)
}

func Lvl3(args ...interface{}) {
	Lvl(3, args...)
}

func Lvl4(args ...interface{}) {
	Lvl(4, args...)
}

func Lvl5(args ...interface{}) {
	Lvl(5, args...)
}

type DebugLvl struct {
}

func (f *DebugLvl) Format(entry *logrus.Entry) ([]byte, error) {
	lvl := entry.Data["debug_lvl"].(int)
	if lvl <= DebugVisible {
		b := &bytes.Buffer{}
		b.WriteString(fmt.Sprintf("%d: %s", lvl, entry.Message))
		b.WriteByte('\n')

		return b.Bytes(), nil
	} else {
		return nil, nil
	}
}

