package debug_lvl
import (
	"fmt"
	"bytes"
	"github.com/Sirupsen/logrus"
	"os"
	"runtime"
	"regexp"
)

// These are information-debugging levels that can be turned on or off.
// Every logging greater than 'DebugVisible' will be discarded. So you can
// Log at different levels and easily turn on or off the amount of logging
// generated by adjusting the 'DebugVisible' variable.
var DebugVisible = 2

// Testing output has to be on fmt, it doesn't take into account log-outputs
// So for testing, set Testing = true, and instead of sending to log, it will
// output to fmt
var Testing = false

// Holds the logrus-structure to do our logging
var DebugLog = &logrus.Logger{
	Out: os.Stdout,
	Formatter: &DebugLvl{},
	Hooks: make(logrus.LevelHooks),
	Level: logrus.InfoLevel}

var regexpPaths, _ = regexp.Compile(".*/")

func init(){
}

func Lvl(lvl int, args ...interface{}) {
	_, file, line, _ := runtime.Caller(2)
	caller := fmt.Sprintf("%s: %d", regexpPaths.ReplaceAllString(file, ""), line)
	DebugLog.WithFields(logrus.Fields{
		"debug_lvl": lvl,
		"caller": caller}).Println(args...)
}

func Lvl1(args ...interface{}) {
	Lvl(1, args...)
}

func Lvl2(args ...interface{}) {
	Lvl(2, args...)
}

func Lvl3(args ...interface{}) {
	Lvl(3, args...)
}

func Lvl4(args ...interface{}) {
	Lvl(4, args...)
}

func Lvl5(args ...interface{}) {
	Lvl(5, args...)
}

type DebugLvl struct {
}

func (f *DebugLvl) Format(entry *logrus.Entry) ([]byte, error) {
	lvl := entry.Data["debug_lvl"].(int)
	caller := entry.Data["caller"].(string)
	if lvl <= DebugVisible {
		b := &bytes.Buffer{}
		b.WriteString(fmt.Sprintf("%d: (%s) - %s", lvl, caller, entry.Message))
		b.WriteByte('\n')

		if Testing {
			fmt.Print(b)
			return nil, nil
		} else {
			return b.Bytes(), nil
		}
	} else {
		return nil, nil
	}
}

