Simulation = "SwUpRandClient"
Servers = 2
Bf = 2
Rounds = 10
CloseWait = 6000
Height = 1
Base = 1
RunWait = 3600
Snapshot = "snapshots_limited_full.csv"
Depth = 2
Delay = 0
Bandwidth = 100

Frequency
1
8
64
256
