Simulation = "SwUpRandClient"
Servers = 2
Bf = 2
Rounds = 10
CloseWait = 6000
Height = 10
Base = 4
RunWait = 3600
Snapshot = "snapshots_limited_6.csv"
Depth = 2
Delay = 50
Bandwidth = 100

Frequency
1
8
64
256
