<<<<<<< HEAD
Simulation = "JVSS"
Servers = 16
Bf = 2
Rounds = 5
CloseWait = 6000

Depth
2
3
4
=======
Simulation = "SimulationJVSS"
Servers = 8
Bf = 1
Rounds = 10
CloseWait = 6000

Hosts, Checking
3, 0
>>>>>>> origin/check
