#!/bin/bash
if ! grep -q backports /etc/apt/sources.list; then
  echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
fi
apt-get update
apt-get install -y openssh-server vim sudo golang-1.6 git psmisc
if [ ! -d /home/linus ]; then
  adduser linus
  adduser linus sudo
  ln -s /home/linus/hp/group.toml /home/linus
fi
if ! grep -q GOPATH /home/linus/.bashrc; then
  cat >> /home/linus/.bashrc <<'EOF'
export GOPATH=~/go
export PATH=$PATH:/usr/lib/go-1.6/bin:$GOPATH/bin:~/hp
sudo /etc/init.d/ssh start
EOF
fi
