# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skipchain/skipchain.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='skipchain/skipchain.proto',
  package='cothority',
  syntax='proto2',
  serialized_pb=_b('\n\x19skipchain/skipchain.proto\x12\tcothority\x1a\x0emessages.proto\",\n\tBlockLink\x12\x0c\n\x04Hash\x18\x01 \x02(\x0c\x12\x11\n\tSignature\x18\x02 \x02(\x0c\"\x9f\x02\n\tSkipBlock\x12\r\n\x05Index\x18\x01 \x01(\x11\x12\x0e\n\x06Height\x18\x02 \x01(\x11\x12\x15\n\rMaximumHeight\x18\x03 \x01(\x11\x12\x12\n\nBaseHeight\x18\x04 \x01(\x11\x12\x13\n\x0b\x42\x61\x63kLinkIDs\x18\x05 \x03(\x0c\x12\x13\n\x0bVerifierIDs\x18\x06 \x03(\x0c\x12\x15\n\rParentBlockID\x18\x07 \x01(\x0c\x12\x11\n\tGenesisID\x18\x08 \x01(\x0c\x12\x0c\n\x04\x44\x61ta\x18\t \x01(\x0c\x12\x1c\n\x06Roster\x18\n \x01(\x0b\x32\x0c.onet.Roster\x12\x0c\n\x04Hash\x18\x0b \x01(\x0c\x12)\n\x0b\x46orwardLink\x18\x0c \x03(\x0b\x32\x14.cothority.BlockLink\x12\x0f\n\x07\x43hildSL\x18\r \x01(\x0c\"?\n\x15StoreSkipBlockRequest\x12&\n\x08NewBlock\x18\x01 \x02(\x0b\x32\x14.cothority.SkipBlock\"f\n\x16StoreSkipBlockResponse\x12&\n\x08Previous\x18\x01 \x02(\x0b\x32\x14.cothority.SkipBlock\x12$\n\x06Latest\x18\x02 \x02(\x0b\x32\x14.cothority.SkipBlock\"A\n\x10GetBlocksRequest\x12\r\n\x05Start\x18\x01 \x02(\x0c\x12\x0b\n\x03\x45nd\x18\x02 \x02(\x0c\x12\x11\n\tMaxHeight\x18\x03 \x02(\x11\"8\n\x11GetBlocksResponse\x12#\n\x05Reply\x18\x01 \x03(\x0b\x32\x14.cothority.SkipBlock\"\x19\n\x17GetAllSkipchainsRequest\">\n\x18GetAllSkipchainsResponse\x12\"\n\x04Last\x18\x01 \x03(\x0b\x32\x14.cothority.SkipBlock')
  ,
  dependencies=[messages__pb2.DESCRIPTOR,])




_BLOCKLINK = _descriptor.Descriptor(
  name='BlockLink',
  full_name='cothority.BlockLink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Hash', full_name='cothority.BlockLink.Hash', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Signature', full_name='cothority.BlockLink.Signature', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=100,
)


_SKIPBLOCK = _descriptor.Descriptor(
  name='SkipBlock',
  full_name='cothority.SkipBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Index', full_name='cothority.SkipBlock.Index', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Height', full_name='cothority.SkipBlock.Height', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MaximumHeight', full_name='cothority.SkipBlock.MaximumHeight', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BaseHeight', full_name='cothority.SkipBlock.BaseHeight', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BackLinkIDs', full_name='cothority.SkipBlock.BackLinkIDs', index=4,
      number=5, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VerifierIDs', full_name='cothority.SkipBlock.VerifierIDs', index=5,
      number=6, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ParentBlockID', full_name='cothority.SkipBlock.ParentBlockID', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GenesisID', full_name='cothority.SkipBlock.GenesisID', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Data', full_name='cothority.SkipBlock.Data', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Roster', full_name='cothority.SkipBlock.Roster', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Hash', full_name='cothority.SkipBlock.Hash', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ForwardLink', full_name='cothority.SkipBlock.ForwardLink', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChildSL', full_name='cothority.SkipBlock.ChildSL', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=390,
)


_STORESKIPBLOCKREQUEST = _descriptor.Descriptor(
  name='StoreSkipBlockRequest',
  full_name='cothority.StoreSkipBlockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='NewBlock', full_name='cothority.StoreSkipBlockRequest.NewBlock', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=455,
)


_STORESKIPBLOCKRESPONSE = _descriptor.Descriptor(
  name='StoreSkipBlockResponse',
  full_name='cothority.StoreSkipBlockResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Previous', full_name='cothority.StoreSkipBlockResponse.Previous', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Latest', full_name='cothority.StoreSkipBlockResponse.Latest', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=559,
)


_GETBLOCKSREQUEST = _descriptor.Descriptor(
  name='GetBlocksRequest',
  full_name='cothority.GetBlocksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Start', full_name='cothority.GetBlocksRequest.Start', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='End', full_name='cothority.GetBlocksRequest.End', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MaxHeight', full_name='cothority.GetBlocksRequest.MaxHeight', index=2,
      number=3, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=626,
)


_GETBLOCKSRESPONSE = _descriptor.Descriptor(
  name='GetBlocksResponse',
  full_name='cothority.GetBlocksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Reply', full_name='cothority.GetBlocksResponse.Reply', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=628,
  serialized_end=684,
)


_GETALLSKIPCHAINSREQUEST = _descriptor.Descriptor(
  name='GetAllSkipchainsRequest',
  full_name='cothority.GetAllSkipchainsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=711,
)


_GETALLSKIPCHAINSRESPONSE = _descriptor.Descriptor(
  name='GetAllSkipchainsResponse',
  full_name='cothority.GetAllSkipchainsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Last', full_name='cothority.GetAllSkipchainsResponse.Last', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=713,
  serialized_end=775,
)

_SKIPBLOCK.fields_by_name['Roster'].message_type = messages__pb2._ROSTER
_SKIPBLOCK.fields_by_name['ForwardLink'].message_type = _BLOCKLINK
_STORESKIPBLOCKREQUEST.fields_by_name['NewBlock'].message_type = _SKIPBLOCK
_STORESKIPBLOCKRESPONSE.fields_by_name['Previous'].message_type = _SKIPBLOCK
_STORESKIPBLOCKRESPONSE.fields_by_name['Latest'].message_type = _SKIPBLOCK
_GETBLOCKSRESPONSE.fields_by_name['Reply'].message_type = _SKIPBLOCK
_GETALLSKIPCHAINSRESPONSE.fields_by_name['Last'].message_type = _SKIPBLOCK
DESCRIPTOR.message_types_by_name['BlockLink'] = _BLOCKLINK
DESCRIPTOR.message_types_by_name['SkipBlock'] = _SKIPBLOCK
DESCRIPTOR.message_types_by_name['StoreSkipBlockRequest'] = _STORESKIPBLOCKREQUEST
DESCRIPTOR.message_types_by_name['StoreSkipBlockResponse'] = _STORESKIPBLOCKRESPONSE
DESCRIPTOR.message_types_by_name['GetBlocksRequest'] = _GETBLOCKSREQUEST
DESCRIPTOR.message_types_by_name['GetBlocksResponse'] = _GETBLOCKSRESPONSE
DESCRIPTOR.message_types_by_name['GetAllSkipchainsRequest'] = _GETALLSKIPCHAINSREQUEST
DESCRIPTOR.message_types_by_name['GetAllSkipchainsResponse'] = _GETALLSKIPCHAINSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlockLink = _reflection.GeneratedProtocolMessageType('BlockLink', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKLINK,
  __module__ = 'skipchain.skipchain_pb2'
  # @@protoc_insertion_point(class_scope:cothority.BlockLink)
  ))
_sym_db.RegisterMessage(BlockLink)

SkipBlock = _reflection.GeneratedProtocolMessageType('SkipBlock', (_message.Message,), dict(
  DESCRIPTOR = _SKIPBLOCK,
  __module__ = 'skipchain.skipchain_pb2'
  # @@protoc_insertion_point(class_scope:cothority.SkipBlock)
  ))
_sym_db.RegisterMessage(SkipBlock)

StoreSkipBlockRequest = _reflection.GeneratedProtocolMessageType('StoreSkipBlockRequest', (_message.Message,), dict(
  DESCRIPTOR = _STORESKIPBLOCKREQUEST,
  __module__ = 'skipchain.skipchain_pb2'
  # @@protoc_insertion_point(class_scope:cothority.StoreSkipBlockRequest)
  ))
_sym_db.RegisterMessage(StoreSkipBlockRequest)

StoreSkipBlockResponse = _reflection.GeneratedProtocolMessageType('StoreSkipBlockResponse', (_message.Message,), dict(
  DESCRIPTOR = _STORESKIPBLOCKRESPONSE,
  __module__ = 'skipchain.skipchain_pb2'
  # @@protoc_insertion_point(class_scope:cothority.StoreSkipBlockResponse)
  ))
_sym_db.RegisterMessage(StoreSkipBlockResponse)

GetBlocksRequest = _reflection.GeneratedProtocolMessageType('GetBlocksRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETBLOCKSREQUEST,
  __module__ = 'skipchain.skipchain_pb2'
  # @@protoc_insertion_point(class_scope:cothority.GetBlocksRequest)
  ))
_sym_db.RegisterMessage(GetBlocksRequest)

GetBlocksResponse = _reflection.GeneratedProtocolMessageType('GetBlocksResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETBLOCKSRESPONSE,
  __module__ = 'skipchain.skipchain_pb2'
  # @@protoc_insertion_point(class_scope:cothority.GetBlocksResponse)
  ))
_sym_db.RegisterMessage(GetBlocksResponse)

GetAllSkipchainsRequest = _reflection.GeneratedProtocolMessageType('GetAllSkipchainsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETALLSKIPCHAINSREQUEST,
  __module__ = 'skipchain.skipchain_pb2'
  # @@protoc_insertion_point(class_scope:cothority.GetAllSkipchainsRequest)
  ))
_sym_db.RegisterMessage(GetAllSkipchainsRequest)

GetAllSkipchainsResponse = _reflection.GeneratedProtocolMessageType('GetAllSkipchainsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETALLSKIPCHAINSRESPONSE,
  __module__ = 'skipchain.skipchain_pb2'
  # @@protoc_insertion_point(class_scope:cothority.GetAllSkipchainsResponse)
  ))
_sym_db.RegisterMessage(GetAllSkipchainsResponse)


# @@protoc_insertion_point(module_scope)
