var SignTest = []T{
	{0, 1, 2, 30, 20, 0, 0, 0, false, "coll_sign"},
	{0, 2, 3, 30, 20, 0, 0, 0, false, "coll_sign"},
	{0, 4, 3, 30, 20, 0, 0, 0, false, "coll_sign"},
	{0, 8, 8, 30, 20, 0, 0, 0, false, "coll_sign"},
	{0, 16, 16, 30, 20, 0, 0, 0, false, "coll_sign"},
	{0, 32, 16, 30, 20, 0, 0, 0, false, "coll_sign"},
	{0, 64, 16, 30, 20, 0, 0, 0, false, "coll_sign"},
	{0, 128, 16, 30, 50, 0, 0, 0, false, "coll_sign"},
}

