func DepthTestFixed(hpn int) []T {
	return []T{
		{0, hpn, 1, 30, DefaultRounds, 0, 0, 0, false, "coll_stamp"},
		{0, hpn, 2, 30, DefaultRounds, 0, 0, 0, false, "coll_stamp"},
		{0, hpn, 4, 30, DefaultRounds, 0, 0, 0, false, "coll_stamp"},
		{0, hpn, 8, 30, DefaultRounds, 0, 0, 0, false, "coll_stamp"},
		{0, hpn, 16, 30, DefaultRounds, 0, 0, 0, false, "coll_stamp"},
		{0, hpn, 32, 30, DefaultRounds, 0, 0, 0, false, "coll_stamp"},
		{0, hpn, 64, 30, DefaultRounds, 0, 0, 0, false, "coll_stamp"},
		{0, hpn, 128, 30, DefaultRounds, 0, 0, 0, false, "coll_stamp"},
		{0, hpn, 256, 30, DefaultRounds, 0, 0, 0, false, "coll_stamp"},
		{0, hpn, 512, 30, DefaultRounds, 0, 0, 0, false, "coll_stamp"},
	}
}
