package randhoundco

import "github.com/dedis/cothority/network"

// SetupReq contains the information to setup a new RandhoundCo system in place.
type SetupReq struct {
	// the groups will be created by splitting this Roster in small groups.
	Entities []*network.ServerIdentity
	// how many groups to create
	// XXX Later this value will be replaced by the output of a Randhound
	// round?
	Groups int
}

// NewRoundReq is used to request to the service a new random output by
// launching a new randhoundco protocol.
type NewRoundReq struct {
	// the id of the randhoundco system we want randomness from. This ID must
	// have been created with first a call to Setup() on the service.
	Id []byte
}

// NewRoundRep contains the randomness generated by a round of a
// Randhoundco. This randomness is the signature and it can be verified
// using the message that helped generating it.
type NewRoundRep struct {
	Msg []byte
	Sig []byte
}
