#!/bin/bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
CSV_DIR=.
CSV_REL=""
PIC="true"
#SHOW="true"
EXT="png"

main(){
  plot_roundtime
#  plot_over
#  plot_bf
#  plot_stamp
}

add_dir(){
  for c in $@; do
    CSV_REL="$CSV_REL $CSV_DIR/$c"
  done
}

plot(){
  if [ "$SHOW" = "true" ]; then
    python2.7 plotit.py $1 $CSV_REL
  fi
  if [ "$PIC" = "true" ]; then
    python2.7 plotit.py $1 $CSV_REL $2.$EXT
  fi
  if [ "$3" != "noclear" ]; then
    CSV_REL=""
  fi
}

plot_roundtime(){
  add_dir cosi_old.csv cosi_depth_3.csv cosi_depth_4.csv cosi_depth_5.csv
  plot 0 comparison_roundtime noclear
  #plot 1 comparison_systime noclear
  #plot 3 comparison_check noclear
  CSV_REL=""
}

plot_over(){
  add_dir sign_over_1.csv sign_over_2.csv sign_over_3.csv
  plot 4 sign_over
}

plot_bf(){
  add_dir sign_multi_bf.csv
  plot 5 sign_multi_bf

  #for bf in 128 512 2048 8192; do
  #  add_dir sign_multi_bf_$bf.csv
  #done
  #plot 7 sign_multi_bf
}

plot_stamp(){
  add_dir stamp_perc100-2.csv
  plot 6 stamp_rate
}
main
