name: Lint, Build, and Test

on:
  pull_request:

env:
  NODE_VERSION: 10
  GO_VERSION: 1.15
  JAVA_VERSION: 9

jobs:
  test-java:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: running tests
        run: make test_java
